import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google"
import { Box, Container, VStack, Heading, Text } from "@chakra-ui/react"
import HomePage from "./home"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>React - Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        className={`${geistSans.variable} ${geistMono.variable}`}
        display="flex"
        alignItems="center"
        justifyContent="center"
      >
        <Container maxW={"full"}>
          <Heading size="lg" textAlign="center" color="blue.500">
            React - Image Uploader
          </Heading>

          <VStack spacing={6} align="stretch">
            <HomePage />
          </VStack>
        </Container>
      </Box>
    </>
  )
}
